export const FETCH_LOG_TYPES_USER_SUCCESS = 'FETCH_LOG_TYPES_USER_SUCCESS';
export const FETCH_LOG_SOURCE_USER_SUCCESS = 'FETCH_LOG_SOURCE_USER_SUCCESS';
export const FETCH_LOG_SOURSE_EVENT_USER_SUCCESS = 'FETCH_LOG_SOURSE_EVENT_USER_SUCCESS';
export const FETCH_LOG_RESULT_USER_SUCCESS = 'FETCH_LOG_RESULT_USER_SUCCESS';

export const FETCH_LOG_TYPES_COMPLEX_SUCCESS = 'FETCH_LOG_TYPES_COMPLEX_SUCCESS';
export const FETCH_LOG_SOURCE_COMPLEX_SUCCESS = 'FETCH_LOG_SOURCE_COMPLEX_SUCCESS';
export const FETCH_LOG_SOURSE_EVENT_COMPLEX_SUCCESS = 'FETCH_LOG_SOURSE_EVENT_COMPLEX_SUCCESS';
export const FETCH_LOG_RESULT_COMPLEX_SUCCESS = 'FETCH_LOG_RESULT_COMPLEX_SUCCESS';

export const FETCH_LOG_TYPES_COMPLEXS_SUCCESS = 'FETCH_LOG_TYPES_COMPLEXS_SUCCESS';
export const FETCH_LOG_SOURCE_COMPLEXS_SUCCESS = 'FETCH_LOG_SOURCE_COMPLEXS_SUCCESS';
export const FETCH_LOG_SOURSE_EVENT_COMPLEXS_SUCCESS = 'FETCH_LOG_SOURSE_EVENT_COMPLEXS_SUCCESS';
export const FETCH_LOG_RESULT_COMPLEXS_SUCCESS = 'FETCH_LOG_RESULT_COMPLEXS_SUCCESS';

export const UPDATE_SUBSYSTEMS = 'UPDATE_SUBSYSTEMS';
export const UPDATE_STATUSES = 'UPDATE_STATUSES';
export const UPDATE_ACTIONS = 'UPDATE_ACTIONS';
export const UPDATE_LEGEND_LIST = 'UPDATE_LEGEND_LIST';

export const SET_ACTIVE_MODE = 'SET_ACTIVE_MODE';
export const SET_SLEEP_MODE = 'SET_SLEEP_MODE';
export const SET_COMPLEX_LIST = 'SET_COMPLEX_LIST';
export const SET_SELECTED_COMPLEX = 'SET_SELECTED_COMPLEX';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_ID_COMPLEX = 'SET_ID_COMPLEX';
export const SET_TELEMETRY_DATA = 'SET_TELEMETRY_DATA';
export const SET_TELEMETRY_AP1_DATA = 'SET_TELEMETRY_AP1_DATA';
export const SET_TELEMETRY_AP2_DATA = 'SET_TELEMETRY_AP2_DATA';
export const SET_VALUE_AP1_DATA = 'SET_VALUE_AP1_DATA';
export const SET_VALUE_AP2_DATA = 'SET_VALUE_AP2_DATA';

